# Generated by Django 4.1.3 on 2022-11-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('key', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=4096)),
                ('ingredients', models.CharField(max_length=2048)),
                ('likes', models.IntegerField(default=0)),
                ('last_updated', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shopper.category')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shopper.country')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopper.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopper.recept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64)),
                ('amount', models.CharField(max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser')),
            ],
        ),
    ]
