# Generated by Django 4.1.3 on 2022-11-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
