# Generated by Django 4.1.3 on 2022-11-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0003_country_recept_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
