# Generated by Django 4.1.3 on 2022-11-24 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0004_alter_recept_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='last_updated',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
