# Generated by Django 4.1.3 on 2022-11-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0005_alter_recept_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='key',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='savedrecept',
            name='user',
            field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser', to_field='key'),
        ),
    ]
