# Generated by Django 4.1.3 on 2022-11-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0006_alter_customuser_key_alter_savedrecept_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser', to_field='key'),
        ),
    ]
