# Generated by Django 4.1.3 on 2022-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0007_alter_basket_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
