# Generated by Django 4.1.3 on 2022-11-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0009_basket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopper.recept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser')),
            ],
        ),
    ]
