# Generated by Django 4.1.3 on 2022-11-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0010_likedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedPost',
        ),
    ]
