# Generated by Django 4.1.3 on 2022-11-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0012_likedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedpost',
            name='user',
            field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser', to_field='key'),
        ),
    ]
