# Generated by Django 4.1.3 on 2022-11-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0013_alter_likedpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser', to_field='key'),
        ),
        migrations.AlterField(
            model_name='likedpost',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser', to_field='key'),
        ),
        migrations.AlterField(
            model_name='savedrecept',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='shopper.customuser', to_field='key'),
        ),
    ]
