# Generated by Django 4.1.3 on 2022-11-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0014_alter_basket_owner_alter_likedpost_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedPost',
        ),
    ]
