# Generated by Django 4.1.3 on 2022-12-01 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0016_likedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='recept',
            name='last_updated',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
