# Generated by Django 4.1.3 on 2022-12-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0017_alter_basket_status_alter_recept_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recept',
            name='ingredients',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
